### ISSUE TITLE
Inability to create notes, use custom folders...

### ISSUE THREAD

**Issue by alex-kovac** [viddo/atom-textual-velocity#65] opened 2017-03-29 15:18 UTC
Hello!

Thank you so much for working on this package NV has been my favorite for years. Having this functionality through Atom is just beautiful.

I am aware velocity is WIP, so before bothering anyone with the details I was wondering if anyone else is having problems/inability to use default folder or custom folders, creating notes...? I would like to know if this is expected considering the stage of development or is it an issue. With the default path not even velocity panel shows up, with custom paths it shows up, but the notes end up in very strange places! E.g: `~/notes/~/Notes/note.md`.

ATM, I have vanilla Atom 1.15.0 x64 on MacOS 10.11.6 (the only package installed is Atom)
(removed all the packages, uninstalled Atom, cleaned the system before this just to make sure it is not my setup creating the problems)

Thanks for any feedback.

**Comment by viddo** [comment] 2017-03-29 16:45
Hi @alex-kovac !

Sounds like a potential bug; I'm using a custom path myself (`/Users/viddo/notes`) and have not experienced any problem like this. From your example (`~/notes/…`) it sounds like there could be some misbehavior due to the ~/ not being resolved properly. I'll investigate further when I have a moment.

Meanwhile, I'd suggest to use a full/absolute path as a workaround.

The package is still WIP yes, but it's mostly missing features. I've been using it on daily basis for months.

**Comment by viddo** [comment] 2017-03-30 03:27
…confirmed that it's indeed a bug. Thanks for reporting it! 🙇 
Just pushed a fix, will release it promptly.

**Closed** 2017-03-30 03:32 UTC
Labels: bug

**Comment by alex-kovac** [comment] 2017-03-30 23:38
Great news @viddo and thanks again!
