### ISSUE TITLE
autosave conflict

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#30] opened 2016-10-08 12:41 UTC
Apparently, autosave does not work. When I enter a new word in the search field and open a new note, the old one is not shown any longer and changes are not saved (although autosave is activated for other documents). I'm not asked whether to keep changes.

I suggest to add autosave and also an option to open new notes in a new tab instead of closing the current note when another one is opened through search.

**Comment by capcionista** [comment] 2016-10-08 12:45
This is not always, but repeatedly the case. I have not been able to determine the pattern yet.

**Comment by viddo** [comment] 2016-10-08 15:16
Oh dear, you find a bug!
Saving/Autosaving is a functionality of Atom itself, and something that doesn't belong in the scope of this package, but I think your suggestion of opening a new tab would be a could solution for this particular use-case.

This is also related to how the notes preview vs. opening will be handled now that I'm working on #25, which will probably resolve this issue too.

**Comment by xHN35RQ** [comment] 2016-10-09 01:55
this bug is on linux as well. The current note closes the moment you start typing into the Search field.

**Comment by xHN35RQ** [comment] 2016-10-09 01:56
@capcionista atom has an autosave package which you can toggle on or off, it should be installed by default: https://atom.io/packages/autosave

**Comment by xHN35RQ** [comment] 2016-10-09 01:57
@capcionista atom has an autosave package which you can toggle on or off, it should be installed by default: https://atom.io/packages/autosave if you have this turned ON I can confirm that changes in the current note are saved before being closed by textual-velocity

**Comment by capcionista** [comment] 2016-10-09 15:54
I was wrong about that: Atom restores all my tabs when I close the window, therefore I thought autosave was enabled, but it wasn't. 
Still, I actually don't want to save my file-history with every switch between two opened tabs (which is included in autosave), because I use dropbox for my notes and it allows me to keep a history of a limited number of versions (I think 7). So I'd really appreciate an option which allows to only save when new note is opened and in general the option to open new notes in a new tab instead of in the same. (Sometimes textual velocity does exactly that, but then again it replaces the current tab).

**Comment by viddo** [comment] 2016-10-14 18:33
Since just releasing a new version (0.10.0) this should no longer be an issue. This package no longer closes any text editors and the new preview pane item is read-only so unaffected by the autosave settings.

**Closed by viddo** 2016-10-14 18:33 UTC
Labels: bug
